// <auto-generated />
namespace squeletteWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class bdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201610101854559_bdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
